spring:
  datasource:
    password: jlm
    url: jdbc:mysql://localhost:3306/mygestock
    username: root
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        jdbc:
          time_zone: UTC
        ejb :
          interceptor: com.mystock.mygestock.interceptor.Interceptor

    auditing:
        enabled: true
        dateTimeProvider: org.springframework.data.jpa.repository.support.JpaAuditingDateTimeProvider

flickr:
  apiKey: a74ab48d977815f07703b6d3f2ee97b9
  apiSecret: 8cf703528d5c218b
  appKey: 72157720876486896-cee34375d2b207c0
  appSecret: 9da854192e7d214c

server:
  port: 8086



